These problems are to do some basic time indexing with pandas. The first code loads in some data from the USGS waterdata site.
<br>[4 pts]

In [1]:
import pandas as pd

url = 'https://waterdata.usgs.gov/tx/nwis/dv?format=rdb&site_no=08108700&referred_module=sw&begin_date=1993-01-01&end_date=2018-10-23'

brazos = pd.read_csv(url, delim_whitespace=True, comment='#', skiprows=[34,], parse_dates=[2, ], index_col=2)
brazos['135330_00060_00003']  # mean daily discharge

datetime
1993-07-14        NaN
1993-07-15        NaN
1993-07-16        NaN
1993-07-17        NaN
1993-07-18        NaN
               ...
2018-10-19    36700.0
2018-10-20    34900.0
2018-10-21    40300.0
2018-10-22    42100.0
2018-10-23    38300.0
Name: 135330_00060_00003, Length: 9233, dtype: float64

Explain in the cell below what each of the options does in the function call to `pd.read_csv` in the cell above:

### These descriptions are taken from the "skills" notebook professor posted on canvas.
delim_whitespace=True - Tells the function to use any kind of whitespace (spaces, TABs) to separate the data.

comment='#' - Tells the function that the '#' character indicates a comment and anything after that character, but on the same line, should be ignored.

skiprows=[35] - Indicates that the line 34 should be skipped. Remember that Python starts counting things from 0. So line 36 of the file is at index 35.

parse_dates=[2,] - Indicates that the third column (at index 2) should be run through the automatic date conversion process. The function will do its best to figure out how the date is formatted and convert it. Usually 95% effective. Sometimes the date and time are in different columns. If we put more column numbers in here, it will combine them first, then try to convert them.

index_col=2 - Tells the function to use the third column (at index 2) as the index for the dataframe. This means it will 'sort' the data by date and we can refer to specific dates of data in the future.

Calculate the mean discharge in 2015 and 2016 and store the values in variables called 'brazos_mean_2016' and 'brazos_mean_2017' <br>
[4 pts]

In [2]:
#Test code for my reference, please ignore.
brazos["1993-07"]

,agency_cd,site_no,135325_00065_00001,135325_00065_00001_cd,135326_00065_00002,135326_00065_00002_cd,135327_00065_00003,135327_00065_00003_cd,135328_00060_00001,135328_00060_00001_cd,135329_00060_00002,135329_00060_00002_cd,135330_00060_00003,135330_00060_00003_cd
datetime,,,,,,,,,,,,,,
1993-07-14,USGS,8108700,2150.00,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-07-15,USGS,8108700,11.30,A,11.24,A,11.26,A,2140.0,A,2110.0,A,NaN,NaN
1993-07-16,USGS,8108700,11.27,A,11.17,A,11.21,A,2120.0,A,2060.0,A,NaN,NaN
1993-07-17,USGS,8108700,11.20,A,11.10,A,11.14,A,2060.0,A,2010.0,A,NaN,NaN
1993-07-18,USGS,8108700,11.16,A,10.72,A,10.90,A,2020.0,A,1810.0,A,NaN,NaN
1993-07-19,USGS,8108700,10.72,A,10.59,A,10.63,A,1670.0,A,1600.0,A,NaN,NaN
1993-07-20,USGS,8108700,10.69,A,10.60,A,10.64,A,1640.0,A,1600.0,A,NaN,NaN
1993-07-21,USGS,8108700,10.72,A,10.58,A,10.65,A,1670.0,A,1610.0,A,NaN,NaN
1993-07-22,USGS,8108700,10.70,A,10.42,A,10.51,A,1650.0,A,1510.0,A,NaN,NaN
1993-07-23,USGS,8108700,10.53,A,10.01,A,10.27,A,1520.0,A,1350.0,A,NaN,NaN
1993-07-24,USGS,8108700,10.26,A,10.01,A,10.09,A,1340.0,A,1240.0,A,NaN,NaN
1993-07-25,USGS,8108700,10.26,A,10.16,A,10.20,A,1340.0,A,1300.0,A,NaN,NaN
1993-07-26,USGS,8108700,10.18,A,10.06,A,10.11,A,1290.0,A,1250.0,A,NaN,NaN
1993-07-27,USGS,8108700,10.12,A,10.04,A,10.08,A,1250.0,A,1230.0,A,NaN,NaN
1993-07-28,USGS,8108700,10.12,A,10.00,A,10.05,A,1250.0,A,1210.0,A,NaN,NaN
1993-07-29,USGS,8108700,10.07,A,9.96,A,10.02,A,1220.0,A,1190.0,A,NaN,NaN
1993-07-30,USGS,8108700,10.48,A,10.06,A,10.23,A,1490.0,A,1330.0,A,NaN,NaN
1993-07-31,USGS,8108700,10.46,A,10.28,A,10.35,A,1470.0,A,1400.0,A,NaN,NaN

In [3]:
# your code here
### BEGIN SOLUTION
brazos_2016 = brazos['135330_00060_00003']['2016'].array
brazos_mean_2016 = brazos_2016.mean()
brazos_2017 = brazos['135330_00060_00003']['2017'].array
brazos_mean_2017 = brazos_2017.mean()
print(brazos_mean_2016,brazos_mean_2017)

13075.825136612022 3443.3698630136987

# I slightly altered the test code. The original code was giving a warning (not an error) that I could not resolve.

In [4]:
assert(brazos_mean_2016==13075.825136612022)
assert(brazos_mean_2017 == 3443.3698630136987)
print("success!")

success!

# The code below is the original test code, and this is the error I keep getting.

In [5]:
assert(brazos_mean_2016, 13075.825136612022)
assert(brazos_mean_2017, 3443.3698630136987)

<>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:2: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:2: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<ipython-input-5-a7cfc71ca33b>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(brazos_mean_2016, 13075.825136612022)
<ipython-input-5-a7cfc71ca33b>:2: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(brazos_mean_2017, 3443.3698630136987)

Compare early summer discharge (May, June, and July) with late summer/fall discharge (August, September, October) in 2016 and 2017. Store your variables with names:

   - brazos_mjj_2016
   - brazos_aso_2016
   - brazos_mjj_2017
   - brazos_aso_2017

In [6]:
# your code here
### BEGIN SOLUTION
mjj16 = brazos['135330_00060_00003']['2016-05':'2016-07'].array
brazos_mjj_2016 = mjj16.mean()
aso16 = brazos['135330_00060_00003']['2016-08':'2016-10'].array
brazos_aso_2016 = aso16.mean()
mjj17 = brazos['135330_00060_00003']['2017-05':'2017-07'].array
brazos_mjj_2017 = mjj17.mean()
aso17 = brazos['135330_00060_00003']['2017-08':'2017-10'].array
brazos_aso_2017 = aso17.mean()

print(brazos_mjj_2016,brazos_aso_2016,brazos_mjj_2017,brazos_aso_2017)

27803.695652173912 4584.945652173913 2802.8804347826085 1657.5217391304348

In [7]:
#My own code for preliminary testing. Please Ignore.
mjj16a = brazos['135330_00060_00003']['2016-05':'2016-07'].array
mjj16a.mean()

27803.695652173912

# I slightly altered the test code. The original code was giving a warning (not an error) that I could not resolve.

In [8]:
assert(brazos_mjj_2016 == 27803.695652173912)
assert(brazos_aso_2016 == 4584.945652173913)
assert(brazos_mjj_2017 == 2802.8804347826085)
assert(brazos_aso_2017 == 1657.5217391304348)
print("Success!")

Success!

# The code below is the original test code, and this is the error I keep getting

In [9]:
assert(brazos_mjj_2016, 27803.695652173912)
assert(brazos_aso_2016, 4584.945652173913)
assert(brazos_mjj_2017, 2802.8804347826085)
assert(brazos_aso_2017, 1657.5217391304348)

<>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:2: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:3: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:2: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:3: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<ipython-input-9-05c1def49b29>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(brazos_mjj_2016, 27803.695652173912)
<ipython-input-9-05c1def49b29>:2: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(brazos_aso_2016, 4584.945652173913)
<ipython-input-9-05c1def49b29>:3: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(brazos_mjj_2017, 2802.8804347826085)
<ipython-input-9-05c1def49b29>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(brazos_aso_2017, 1657.5217391304348)